version: "2"

run:
  timeout: 5m
  tests: false
  issues-exit-code: 0

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true
    code-climate:
      path: gl-code-quality-report.json

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unparam
    - sqlclosecheck
    - unconvert
    - noctx
    - gocritic
    - dogsled
    - nolintlint
    - misspell
    - prealloc
    - gocognit
    - gosec
  settings:
    gocritic:
      disabled-checks:
        - commentFormatting
    gocognit:
      # minimal code complexity to report (we recommend 10-20, using 40 here)
      min-complexity: 40
    errcheck:
      check-blank: true
      check-type-assertions: true
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "SA1019:"
      - linters:
          - gosec
        text: "G402:"
      - linters:
          - gocritic
        text: "singleCaseSwitch:"

severity:
  default: info
