// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package main

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *LargeNestedStruct) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Field1":
			z.Field1, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Field1")
				return
			}
		case "Field2":
			z.Field2, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Field2")
				return
			}
		case "Field3":
			z.Field3, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Field3")
				return
			}
		case "Field4":
			z.Field4, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Field4")
				return
			}
		case "Field5":
			z.Field5, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Field5")
				return
			}
		case "Nested1":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Nested1")
				return
			}
			for zb0002 > 0 {
				zb0002--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Nested1")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested1.SubField1, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Nested1", "SubField1")
						return
					}
				case "SubField2":
					z.Nested1.SubField2, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "Nested1", "SubField2")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Nested1")
						return
					}
				}
			}
		case "Nested2":
			var zb0003 uint32
			zb0003, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Nested2")
				return
			}
			for zb0003 > 0 {
				zb0003--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Nested2")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested2.SubField1, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Nested2", "SubField1")
						return
					}
				case "SubField2":
					z.Nested2.SubField2, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "Nested2", "SubField2")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Nested2")
						return
					}
				}
			}
		case "Nested3":
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Nested3")
				return
			}
			for zb0004 > 0 {
				zb0004--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Nested3")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested3.SubField1, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Nested3", "SubField1")
						return
					}
				case "SubField2":
					z.Nested3.SubField2, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "Nested3", "SubField2")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Nested3")
						return
					}
				}
			}
		case "Nested4":
			var zb0005 uint32
			zb0005, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Nested4")
				return
			}
			for zb0005 > 0 {
				zb0005--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Nested4")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested4.SubField1, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Nested4", "SubField1")
						return
					}
				case "SubField2":
					z.Nested4.SubField2, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "Nested4", "SubField2")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Nested4")
						return
					}
				}
			}
		case "Nested5":
			var zb0006 uint32
			zb0006, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Nested5")
				return
			}
			for zb0006 > 0 {
				zb0006--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Nested5")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested5.SubField1, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Nested5", "SubField1")
						return
					}
				case "SubField2":
					z.Nested5.SubField2, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "Nested5", "SubField2")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Nested5")
						return
					}
				}
			}
		case "Nested6":
			var zb0007 uint32
			zb0007, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Nested6")
				return
			}
			for zb0007 > 0 {
				zb0007--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Nested6")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested6.SubField1, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Nested6", "SubField1")
						return
					}
				case "SubField2":
					z.Nested6.SubField2, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "Nested6", "SubField2")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Nested6")
						return
					}
				}
			}
		case "Nested7":
			var zb0008 uint32
			zb0008, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Nested7")
				return
			}
			for zb0008 > 0 {
				zb0008--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Nested7")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested7.SubField1, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Nested7", "SubField1")
						return
					}
				case "SubField2":
					z.Nested7.SubField2, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "Nested7", "SubField2")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Nested7")
						return
					}
				}
			}
		case "Nested8":
			var zb0009 uint32
			zb0009, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Nested8")
				return
			}
			for zb0009 > 0 {
				zb0009--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Nested8")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested8.SubField1, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Nested8", "SubField1")
						return
					}
				case "SubField2":
					z.Nested8.SubField2, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "Nested8", "SubField2")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Nested8")
						return
					}
				}
			}
		case "Nested9":
			var zb0010 uint32
			zb0010, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Nested9")
				return
			}
			for zb0010 > 0 {
				zb0010--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Nested9")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested9.SubField1, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Nested9", "SubField1")
						return
					}
				case "SubField2":
					z.Nested9.SubField2, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "Nested9", "SubField2")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Nested9")
						return
					}
				}
			}
		case "Nested10":
			var zb0011 uint32
			zb0011, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Nested10")
				return
			}
			for zb0011 > 0 {
				zb0011--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Nested10")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested10.SubField1, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Nested10", "SubField1")
						return
					}
				case "SubField2":
					z.Nested10.SubField2, err = dc.ReadInt()
					if err != nil {
						err = msgp.WrapError(err, "Nested10", "SubField2")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Nested10")
						return
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *LargeNestedStruct) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 15
	// write "Field1"
	err = en.Append(0x8f, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Field1)
	if err != nil {
		err = msgp.WrapError(err, "Field1")
		return
	}
	// write "Field2"
	err = en.Append(0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Field2)
	if err != nil {
		err = msgp.WrapError(err, "Field2")
		return
	}
	// write "Field3"
	err = en.Append(0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x33)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Field3)
	if err != nil {
		err = msgp.WrapError(err, "Field3")
		return
	}
	// write "Field4"
	err = en.Append(0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x34)
	if err != nil {
		return
	}
	err = en.WriteString(z.Field4)
	if err != nil {
		err = msgp.WrapError(err, "Field4")
		return
	}
	// write "Field5"
	err = en.Append(0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x35)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Field5)
	if err != nil {
		err = msgp.WrapError(err, "Field5")
		return
	}
	// write "Nested1"
	err = en.Append(0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x31)
	if err != nil {
		return
	}
	// map header, size 2
	// write "SubField1"
	err = en.Append(0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Nested1.SubField1)
	if err != nil {
		err = msgp.WrapError(err, "Nested1", "SubField1")
		return
	}
	// write "SubField2"
	err = en.Append(0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Nested1.SubField2)
	if err != nil {
		err = msgp.WrapError(err, "Nested1", "SubField2")
		return
	}
	// write "Nested2"
	err = en.Append(0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x32)
	if err != nil {
		return
	}
	// map header, size 2
	// write "SubField1"
	err = en.Append(0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Nested2.SubField1)
	if err != nil {
		err = msgp.WrapError(err, "Nested2", "SubField1")
		return
	}
	// write "SubField2"
	err = en.Append(0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Nested2.SubField2)
	if err != nil {
		err = msgp.WrapError(err, "Nested2", "SubField2")
		return
	}
	// write "Nested3"
	err = en.Append(0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x33)
	if err != nil {
		return
	}
	// map header, size 2
	// write "SubField1"
	err = en.Append(0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Nested3.SubField1)
	if err != nil {
		err = msgp.WrapError(err, "Nested3", "SubField1")
		return
	}
	// write "SubField2"
	err = en.Append(0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Nested3.SubField2)
	if err != nil {
		err = msgp.WrapError(err, "Nested3", "SubField2")
		return
	}
	// write "Nested4"
	err = en.Append(0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x34)
	if err != nil {
		return
	}
	// map header, size 2
	// write "SubField1"
	err = en.Append(0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Nested4.SubField1)
	if err != nil {
		err = msgp.WrapError(err, "Nested4", "SubField1")
		return
	}
	// write "SubField2"
	err = en.Append(0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Nested4.SubField2)
	if err != nil {
		err = msgp.WrapError(err, "Nested4", "SubField2")
		return
	}
	// write "Nested5"
	err = en.Append(0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x35)
	if err != nil {
		return
	}
	// map header, size 2
	// write "SubField1"
	err = en.Append(0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Nested5.SubField1)
	if err != nil {
		err = msgp.WrapError(err, "Nested5", "SubField1")
		return
	}
	// write "SubField2"
	err = en.Append(0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Nested5.SubField2)
	if err != nil {
		err = msgp.WrapError(err, "Nested5", "SubField2")
		return
	}
	// write "Nested6"
	err = en.Append(0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x36)
	if err != nil {
		return
	}
	// map header, size 2
	// write "SubField1"
	err = en.Append(0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Nested6.SubField1)
	if err != nil {
		err = msgp.WrapError(err, "Nested6", "SubField1")
		return
	}
	// write "SubField2"
	err = en.Append(0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Nested6.SubField2)
	if err != nil {
		err = msgp.WrapError(err, "Nested6", "SubField2")
		return
	}
	// write "Nested7"
	err = en.Append(0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x37)
	if err != nil {
		return
	}
	// map header, size 2
	// write "SubField1"
	err = en.Append(0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Nested7.SubField1)
	if err != nil {
		err = msgp.WrapError(err, "Nested7", "SubField1")
		return
	}
	// write "SubField2"
	err = en.Append(0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Nested7.SubField2)
	if err != nil {
		err = msgp.WrapError(err, "Nested7", "SubField2")
		return
	}
	// write "Nested8"
	err = en.Append(0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x38)
	if err != nil {
		return
	}
	// map header, size 2
	// write "SubField1"
	err = en.Append(0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Nested8.SubField1)
	if err != nil {
		err = msgp.WrapError(err, "Nested8", "SubField1")
		return
	}
	// write "SubField2"
	err = en.Append(0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Nested8.SubField2)
	if err != nil {
		err = msgp.WrapError(err, "Nested8", "SubField2")
		return
	}
	// write "Nested9"
	err = en.Append(0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x39)
	if err != nil {
		return
	}
	// map header, size 2
	// write "SubField1"
	err = en.Append(0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Nested9.SubField1)
	if err != nil {
		err = msgp.WrapError(err, "Nested9", "SubField1")
		return
	}
	// write "SubField2"
	err = en.Append(0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Nested9.SubField2)
	if err != nil {
		err = msgp.WrapError(err, "Nested9", "SubField2")
		return
	}
	// write "Nested10"
	err = en.Append(0xa8, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x31, 0x30)
	if err != nil {
		return
	}
	// map header, size 2
	// write "SubField1"
	err = en.Append(0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Nested10.SubField1)
	if err != nil {
		err = msgp.WrapError(err, "Nested10", "SubField1")
		return
	}
	// write "SubField2"
	err = en.Append(0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Nested10.SubField2)
	if err != nil {
		err = msgp.WrapError(err, "Nested10", "SubField2")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *LargeNestedStruct) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 15
	// string "Field1"
	o = append(o, 0x8f, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	o = msgp.AppendString(o, z.Field1)
	// string "Field2"
	o = append(o, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	o = msgp.AppendInt(o, z.Field2)
	// string "Field3"
	o = append(o, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x33)
	o = msgp.AppendBool(o, z.Field3)
	// string "Field4"
	o = append(o, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x34)
	o = msgp.AppendString(o, z.Field4)
	// string "Field5"
	o = append(o, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x35)
	o = msgp.AppendInt(o, z.Field5)
	// string "Nested1"
	o = append(o, 0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x31)
	// map header, size 2
	// string "SubField1"
	o = append(o, 0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	o = msgp.AppendString(o, z.Nested1.SubField1)
	// string "SubField2"
	o = append(o, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	o = msgp.AppendInt(o, z.Nested1.SubField2)
	// string "Nested2"
	o = append(o, 0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x32)
	// map header, size 2
	// string "SubField1"
	o = append(o, 0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	o = msgp.AppendString(o, z.Nested2.SubField1)
	// string "SubField2"
	o = append(o, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	o = msgp.AppendInt(o, z.Nested2.SubField2)
	// string "Nested3"
	o = append(o, 0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x33)
	// map header, size 2
	// string "SubField1"
	o = append(o, 0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	o = msgp.AppendString(o, z.Nested3.SubField1)
	// string "SubField2"
	o = append(o, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	o = msgp.AppendInt(o, z.Nested3.SubField2)
	// string "Nested4"
	o = append(o, 0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x34)
	// map header, size 2
	// string "SubField1"
	o = append(o, 0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	o = msgp.AppendString(o, z.Nested4.SubField1)
	// string "SubField2"
	o = append(o, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	o = msgp.AppendInt(o, z.Nested4.SubField2)
	// string "Nested5"
	o = append(o, 0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x35)
	// map header, size 2
	// string "SubField1"
	o = append(o, 0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	o = msgp.AppendString(o, z.Nested5.SubField1)
	// string "SubField2"
	o = append(o, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	o = msgp.AppendInt(o, z.Nested5.SubField2)
	// string "Nested6"
	o = append(o, 0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x36)
	// map header, size 2
	// string "SubField1"
	o = append(o, 0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	o = msgp.AppendString(o, z.Nested6.SubField1)
	// string "SubField2"
	o = append(o, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	o = msgp.AppendInt(o, z.Nested6.SubField2)
	// string "Nested7"
	o = append(o, 0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x37)
	// map header, size 2
	// string "SubField1"
	o = append(o, 0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	o = msgp.AppendString(o, z.Nested7.SubField1)
	// string "SubField2"
	o = append(o, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	o = msgp.AppendInt(o, z.Nested7.SubField2)
	// string "Nested8"
	o = append(o, 0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x38)
	// map header, size 2
	// string "SubField1"
	o = append(o, 0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	o = msgp.AppendString(o, z.Nested8.SubField1)
	// string "SubField2"
	o = append(o, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	o = msgp.AppendInt(o, z.Nested8.SubField2)
	// string "Nested9"
	o = append(o, 0xa7, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x39)
	// map header, size 2
	// string "SubField1"
	o = append(o, 0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	o = msgp.AppendString(o, z.Nested9.SubField1)
	// string "SubField2"
	o = append(o, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	o = msgp.AppendInt(o, z.Nested9.SubField2)
	// string "Nested10"
	o = append(o, 0xa8, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x31, 0x30)
	// map header, size 2
	// string "SubField1"
	o = append(o, 0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	o = msgp.AppendString(o, z.Nested10.SubField1)
	// string "SubField2"
	o = append(o, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	o = msgp.AppendInt(o, z.Nested10.SubField2)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *LargeNestedStruct) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Field1":
			z.Field1, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field1")
				return
			}
		case "Field2":
			z.Field2, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field2")
				return
			}
		case "Field3":
			z.Field3, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field3")
				return
			}
		case "Field4":
			z.Field4, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field4")
				return
			}
		case "Field5":
			z.Field5, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field5")
				return
			}
		case "Nested1":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nested1")
				return
			}
			for zb0002 > 0 {
				zb0002--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Nested1")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested1.SubField1, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested1", "SubField1")
						return
					}
				case "SubField2":
					z.Nested1.SubField2, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested1", "SubField2")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested1")
						return
					}
				}
			}
		case "Nested2":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nested2")
				return
			}
			for zb0003 > 0 {
				zb0003--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Nested2")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested2.SubField1, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested2", "SubField1")
						return
					}
				case "SubField2":
					z.Nested2.SubField2, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested2", "SubField2")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested2")
						return
					}
				}
			}
		case "Nested3":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nested3")
				return
			}
			for zb0004 > 0 {
				zb0004--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Nested3")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested3.SubField1, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested3", "SubField1")
						return
					}
				case "SubField2":
					z.Nested3.SubField2, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested3", "SubField2")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested3")
						return
					}
				}
			}
		case "Nested4":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nested4")
				return
			}
			for zb0005 > 0 {
				zb0005--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Nested4")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested4.SubField1, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested4", "SubField1")
						return
					}
				case "SubField2":
					z.Nested4.SubField2, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested4", "SubField2")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested4")
						return
					}
				}
			}
		case "Nested5":
			var zb0006 uint32
			zb0006, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nested5")
				return
			}
			for zb0006 > 0 {
				zb0006--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Nested5")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested5.SubField1, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested5", "SubField1")
						return
					}
				case "SubField2":
					z.Nested5.SubField2, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested5", "SubField2")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested5")
						return
					}
				}
			}
		case "Nested6":
			var zb0007 uint32
			zb0007, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nested6")
				return
			}
			for zb0007 > 0 {
				zb0007--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Nested6")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested6.SubField1, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested6", "SubField1")
						return
					}
				case "SubField2":
					z.Nested6.SubField2, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested6", "SubField2")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested6")
						return
					}
				}
			}
		case "Nested7":
			var zb0008 uint32
			zb0008, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nested7")
				return
			}
			for zb0008 > 0 {
				zb0008--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Nested7")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested7.SubField1, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested7", "SubField1")
						return
					}
				case "SubField2":
					z.Nested7.SubField2, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested7", "SubField2")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested7")
						return
					}
				}
			}
		case "Nested8":
			var zb0009 uint32
			zb0009, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nested8")
				return
			}
			for zb0009 > 0 {
				zb0009--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Nested8")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested8.SubField1, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested8", "SubField1")
						return
					}
				case "SubField2":
					z.Nested8.SubField2, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested8", "SubField2")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested8")
						return
					}
				}
			}
		case "Nested9":
			var zb0010 uint32
			zb0010, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nested9")
				return
			}
			for zb0010 > 0 {
				zb0010--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Nested9")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested9.SubField1, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested9", "SubField1")
						return
					}
				case "SubField2":
					z.Nested9.SubField2, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested9", "SubField2")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested9")
						return
					}
				}
			}
		case "Nested10":
			var zb0011 uint32
			zb0011, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nested10")
				return
			}
			for zb0011 > 0 {
				zb0011--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Nested10")
					return
				}
				switch msgp.UnsafeString(field) {
				case "SubField1":
					z.Nested10.SubField1, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested10", "SubField1")
						return
					}
				case "SubField2":
					z.Nested10.SubField2, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested10", "SubField2")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Nested10")
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LargeNestedStruct) Msgsize() (s int) {
	s = 1 + 7 + msgp.StringPrefixSize + len(z.Field1) + 7 + msgp.IntSize + 7 + msgp.BoolSize + 7 + msgp.StringPrefixSize + len(z.Field4) + 7 + msgp.IntSize + 8 + 1 + 10 + msgp.StringPrefixSize + len(z.Nested1.SubField1) + 10 + msgp.IntSize + 8 + 1 + 10 + msgp.StringPrefixSize + len(z.Nested2.SubField1) + 10 + msgp.IntSize + 8 + 1 + 10 + msgp.StringPrefixSize + len(z.Nested3.SubField1) + 10 + msgp.IntSize + 8 + 1 + 10 + msgp.StringPrefixSize + len(z.Nested4.SubField1) + 10 + msgp.IntSize + 8 + 1 + 10 + msgp.StringPrefixSize + len(z.Nested5.SubField1) + 10 + msgp.IntSize + 8 + 1 + 10 + msgp.StringPrefixSize + len(z.Nested6.SubField1) + 10 + msgp.IntSize + 8 + 1 + 10 + msgp.StringPrefixSize + len(z.Nested7.SubField1) + 10 + msgp.IntSize + 8 + 1 + 10 + msgp.StringPrefixSize + len(z.Nested8.SubField1) + 10 + msgp.IntSize + 8 + 1 + 10 + msgp.StringPrefixSize + len(z.Nested9.SubField1) + 10 + msgp.IntSize + 9 + 1 + 10 + msgp.StringPrefixSize + len(z.Nested10.SubField1) + 10 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *LargeStruct) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "MediumStruct":
			err = z.MediumStruct.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "MediumStruct")
				return
			}
		case "Field11":
			z.Field11, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Field11")
				return
			}
		case "Field12":
			z.Field12, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Field12")
				return
			}
		case "Field13":
			z.Field13, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Field13")
				return
			}
		case "Field14":
			z.Field14, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Field14")
				return
			}
		case "Field15":
			z.Field15, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Field15")
				return
			}
		case "Field16":
			z.Field16, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Field16")
				return
			}
		case "Field17":
			z.Field17, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Field17")
				return
			}
		case "Field18":
			z.Field18, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Field18")
				return
			}
		case "Field19":
			z.Field19, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Field19")
				return
			}
		case "Field20":
			z.Field20, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Field20")
				return
			}
		case "Field21":
			z.Field21, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Field21")
				return
			}
		case "Field22":
			z.Field22, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Field22")
				return
			}
		case "Field23":
			z.Field23, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Field23")
				return
			}
		case "Field24":
			z.Field24, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Field24")
				return
			}
		case "Field25":
			z.Field25, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Field25")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *LargeStruct) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 16
	// write "MediumStruct"
	err = en.Append(0xde, 0x0, 0x10, 0xac, 0x4d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74)
	if err != nil {
		return
	}
	err = z.MediumStruct.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "MediumStruct")
		return
	}
	// write "Field11"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Field11)
	if err != nil {
		err = msgp.WrapError(err, "Field11")
		return
	}
	// write "Field12"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Field12)
	if err != nil {
		err = msgp.WrapError(err, "Field12")
		return
	}
	// write "Field13"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x33)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Field13)
	if err != nil {
		err = msgp.WrapError(err, "Field13")
		return
	}
	// write "Field14"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x34)
	if err != nil {
		return
	}
	err = en.WriteString(z.Field14)
	if err != nil {
		err = msgp.WrapError(err, "Field14")
		return
	}
	// write "Field15"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x35)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Field15)
	if err != nil {
		err = msgp.WrapError(err, "Field15")
		return
	}
	// write "Field16"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x36)
	if err != nil {
		return
	}
	err = en.WriteString(z.Field16)
	if err != nil {
		err = msgp.WrapError(err, "Field16")
		return
	}
	// write "Field17"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x37)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Field17)
	if err != nil {
		err = msgp.WrapError(err, "Field17")
		return
	}
	// write "Field18"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x38)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Field18)
	if err != nil {
		err = msgp.WrapError(err, "Field18")
		return
	}
	// write "Field19"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x39)
	if err != nil {
		return
	}
	err = en.WriteString(z.Field19)
	if err != nil {
		err = msgp.WrapError(err, "Field19")
		return
	}
	// write "Field20"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x30)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Field20)
	if err != nil {
		err = msgp.WrapError(err, "Field20")
		return
	}
	// write "Field21"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Field21)
	if err != nil {
		err = msgp.WrapError(err, "Field21")
		return
	}
	// write "Field22"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Field22)
	if err != nil {
		err = msgp.WrapError(err, "Field22")
		return
	}
	// write "Field23"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x33)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Field23)
	if err != nil {
		err = msgp.WrapError(err, "Field23")
		return
	}
	// write "Field24"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x34)
	if err != nil {
		return
	}
	err = en.WriteString(z.Field24)
	if err != nil {
		err = msgp.WrapError(err, "Field24")
		return
	}
	// write "Field25"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x35)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Field25)
	if err != nil {
		err = msgp.WrapError(err, "Field25")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *LargeStruct) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 16
	// string "MediumStruct"
	o = append(o, 0xde, 0x0, 0x10, 0xac, 0x4d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74)
	o, err = z.MediumStruct.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "MediumStruct")
		return
	}
	// string "Field11"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x31)
	o = msgp.AppendString(o, z.Field11)
	// string "Field12"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x32)
	o = msgp.AppendInt(o, z.Field12)
	// string "Field13"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x33)
	o = msgp.AppendBool(o, z.Field13)
	// string "Field14"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x34)
	o = msgp.AppendString(o, z.Field14)
	// string "Field15"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x35)
	o = msgp.AppendInt(o, z.Field15)
	// string "Field16"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x36)
	o = msgp.AppendString(o, z.Field16)
	// string "Field17"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x37)
	o = msgp.AppendInt(o, z.Field17)
	// string "Field18"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x38)
	o = msgp.AppendBool(o, z.Field18)
	// string "Field19"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x39)
	o = msgp.AppendString(o, z.Field19)
	// string "Field20"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x30)
	o = msgp.AppendInt(o, z.Field20)
	// string "Field21"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x31)
	o = msgp.AppendString(o, z.Field21)
	// string "Field22"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x32)
	o = msgp.AppendInt(o, z.Field22)
	// string "Field23"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x33)
	o = msgp.AppendBool(o, z.Field23)
	// string "Field24"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x34)
	o = msgp.AppendString(o, z.Field24)
	// string "Field25"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32, 0x35)
	o = msgp.AppendInt(o, z.Field25)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *LargeStruct) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "MediumStruct":
			bts, err = z.MediumStruct.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "MediumStruct")
				return
			}
		case "Field11":
			z.Field11, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field11")
				return
			}
		case "Field12":
			z.Field12, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field12")
				return
			}
		case "Field13":
			z.Field13, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field13")
				return
			}
		case "Field14":
			z.Field14, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field14")
				return
			}
		case "Field15":
			z.Field15, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field15")
				return
			}
		case "Field16":
			z.Field16, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field16")
				return
			}
		case "Field17":
			z.Field17, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field17")
				return
			}
		case "Field18":
			z.Field18, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field18")
				return
			}
		case "Field19":
			z.Field19, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field19")
				return
			}
		case "Field20":
			z.Field20, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field20")
				return
			}
		case "Field21":
			z.Field21, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field21")
				return
			}
		case "Field22":
			z.Field22, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field22")
				return
			}
		case "Field23":
			z.Field23, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field23")
				return
			}
		case "Field24":
			z.Field24, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field24")
				return
			}
		case "Field25":
			z.Field25, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field25")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *LargeStruct) Msgsize() (s int) {
	s = 3 + 13 + z.MediumStruct.Msgsize() + 8 + msgp.StringPrefixSize + len(z.Field11) + 8 + msgp.IntSize + 8 + msgp.BoolSize + 8 + msgp.StringPrefixSize + len(z.Field14) + 8 + msgp.IntSize + 8 + msgp.StringPrefixSize + len(z.Field16) + 8 + msgp.IntSize + 8 + msgp.BoolSize + 8 + msgp.StringPrefixSize + len(z.Field19) + 8 + msgp.IntSize + 8 + msgp.StringPrefixSize + len(z.Field21) + 8 + msgp.IntSize + 8 + msgp.BoolSize + 8 + msgp.StringPrefixSize + len(z.Field24) + 8 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MediumStruct) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SmallStruct":
			err = z.SmallStruct.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "SmallStruct")
				return
			}
		case "Field6":
			z.Field6, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Field6")
				return
			}
		case "Field7":
			z.Field7, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Field7")
				return
			}
		case "Field8":
			z.Field8, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Field8")
				return
			}
		case "Field9":
			z.Field9, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Field9")
				return
			}
		case "Field10":
			z.Field10, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Field10")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MediumStruct) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 6
	// write "SmallStruct"
	err = en.Append(0x86, 0xab, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74)
	if err != nil {
		return
	}
	err = z.SmallStruct.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "SmallStruct")
		return
	}
	// write "Field6"
	err = en.Append(0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x36)
	if err != nil {
		return
	}
	err = en.WriteString(z.Field6)
	if err != nil {
		err = msgp.WrapError(err, "Field6")
		return
	}
	// write "Field7"
	err = en.Append(0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x37)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Field7)
	if err != nil {
		err = msgp.WrapError(err, "Field7")
		return
	}
	// write "Field8"
	err = en.Append(0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x38)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Field8)
	if err != nil {
		err = msgp.WrapError(err, "Field8")
		return
	}
	// write "Field9"
	err = en.Append(0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x39)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.Field9)
	if err != nil {
		err = msgp.WrapError(err, "Field9")
		return
	}
	// write "Field10"
	err = en.Append(0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x30)
	if err != nil {
		return
	}
	err = en.WriteString(z.Field10)
	if err != nil {
		err = msgp.WrapError(err, "Field10")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MediumStruct) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 6
	// string "SmallStruct"
	o = append(o, 0x86, 0xab, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74)
	o, err = z.SmallStruct.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "SmallStruct")
		return
	}
	// string "Field6"
	o = append(o, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x36)
	o = msgp.AppendString(o, z.Field6)
	// string "Field7"
	o = append(o, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x37)
	o = msgp.AppendInt(o, z.Field7)
	// string "Field8"
	o = append(o, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x38)
	o = msgp.AppendBool(o, z.Field8)
	// string "Field9"
	o = append(o, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x39)
	o = msgp.AppendFloat64(o, z.Field9)
	// string "Field10"
	o = append(o, 0xa7, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31, 0x30)
	o = msgp.AppendString(o, z.Field10)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MediumStruct) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SmallStruct":
			bts, err = z.SmallStruct.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "SmallStruct")
				return
			}
		case "Field6":
			z.Field6, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field6")
				return
			}
		case "Field7":
			z.Field7, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field7")
				return
			}
		case "Field8":
			z.Field8, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field8")
				return
			}
		case "Field9":
			z.Field9, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field9")
				return
			}
		case "Field10":
			z.Field10, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field10")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MediumStruct) Msgsize() (s int) {
	s = 1 + 12 + z.SmallStruct.Msgsize() + 7 + msgp.StringPrefixSize + len(z.Field6) + 7 + msgp.IntSize + 7 + msgp.BoolSize + 7 + msgp.Float64Size + 8 + msgp.StringPrefixSize + len(z.Field10)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SmallStruct) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Field1":
			z.Field1, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Field1")
				return
			}
		case "Field2":
			z.Field2, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Field2")
				return
			}
		case "Field3":
			z.Field3, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Field3")
				return
			}
		case "Field4":
			z.Field4, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Field4")
				return
			}
		case "Field5":
			z.Field5, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Field5")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SmallStruct) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "Field1"
	err = en.Append(0x85, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.Field1)
	if err != nil {
		err = msgp.WrapError(err, "Field1")
		return
	}
	// write "Field2"
	err = en.Append(0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Field2)
	if err != nil {
		err = msgp.WrapError(err, "Field2")
		return
	}
	// write "Field3"
	err = en.Append(0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x33)
	if err != nil {
		return
	}
	err = en.WriteBool(z.Field3)
	if err != nil {
		err = msgp.WrapError(err, "Field3")
		return
	}
	// write "Field4"
	err = en.Append(0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x34)
	if err != nil {
		return
	}
	err = en.WriteString(z.Field4)
	if err != nil {
		err = msgp.WrapError(err, "Field4")
		return
	}
	// write "Field5"
	err = en.Append(0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x35)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Field5)
	if err != nil {
		err = msgp.WrapError(err, "Field5")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SmallStruct) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "Field1"
	o = append(o, 0x85, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	o = msgp.AppendString(o, z.Field1)
	// string "Field2"
	o = append(o, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	o = msgp.AppendInt(o, z.Field2)
	// string "Field3"
	o = append(o, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x33)
	o = msgp.AppendBool(o, z.Field3)
	// string "Field4"
	o = append(o, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x34)
	o = msgp.AppendString(o, z.Field4)
	// string "Field5"
	o = append(o, 0xa6, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x35)
	o = msgp.AppendInt(o, z.Field5)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SmallStruct) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Field1":
			z.Field1, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field1")
				return
			}
		case "Field2":
			z.Field2, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field2")
				return
			}
		case "Field3":
			z.Field3, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field3")
				return
			}
		case "Field4":
			z.Field4, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field4")
				return
			}
		case "Field5":
			z.Field5, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Field5")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SmallStruct) Msgsize() (s int) {
	s = 1 + 7 + msgp.StringPrefixSize + len(z.Field1) + 7 + msgp.IntSize + 7 + msgp.BoolSize + 7 + msgp.StringPrefixSize + len(z.Field4) + 7 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SubStruct) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SubField1":
			z.SubField1, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SubField1")
				return
			}
		case "SubField2":
			z.SubField2, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "SubField2")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z SubStruct) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "SubField1"
	err = en.Append(0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	if err != nil {
		return
	}
	err = en.WriteString(z.SubField1)
	if err != nil {
		err = msgp.WrapError(err, "SubField1")
		return
	}
	// write "SubField2"
	err = en.Append(0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt(z.SubField2)
	if err != nil {
		err = msgp.WrapError(err, "SubField2")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z SubStruct) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "SubField1"
	o = append(o, 0x82, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x31)
	o = msgp.AppendString(o, z.SubField1)
	// string "SubField2"
	o = append(o, 0xa9, 0x53, 0x75, 0x62, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x32)
	o = msgp.AppendInt(o, z.SubField2)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SubStruct) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SubField1":
			z.SubField1, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SubField1")
				return
			}
		case "SubField2":
			z.SubField2, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SubField2")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z SubStruct) Msgsize() (s int) {
	s = 1 + 10 + msgp.StringPrefixSize + len(z.SubField1) + 10 + msgp.IntSize
	return
}
