// Code generated by MockGen. DO NOT EDIT.
// Source: parser.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/parser.go -source=parser.go -package=headermock
//

// Package headermock is a generated GoMock package.
package headermock

import (
	http "net/http"
	reflect "reflect"

	header "github.com/trinhdaiphuc/go-kit/header"
	gomock "go.uber.org/mock/gomock"
)

// MockParser is a mock of Parser interface.
type MockParser struct {
	ctrl     *gomock.Controller
	recorder *MockParserMockRecorder
	isgomock struct{}
}

// MockParserMockRecorder is the mock recorder for MockParser.
type MockParserMockRecorder struct {
	mock *MockParser
}

// NewMockParser creates a new mock instance.
func NewMockParser(ctrl *gomock.Controller) *MockParser {
	mock := &MockParser{ctrl: ctrl}
	mock.recorder = &MockParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParser) EXPECT() *MockParserMockRecorder {
	return m.recorder
}

// ParseHeader mocks base method.
func (m *MockParser) ParseHeader(headers http.Header) (*header.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseHeader", headers)
	ret0, _ := ret[0].(*header.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseHeader indicates an expected call of ParseHeader.
func (mr *MockParserMockRecorder) ParseHeader(headers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseHeader", reflect.TypeOf((*MockParser)(nil).ParseHeader), headers)
}
