// Code generated by MockGen. DO NOT EDIT.
// Source: consumer_handler.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/consumer_handler.go -source=consumer_handler.go -package=kafkamock
//

// Package kafkamock is a generated GoMock package.
package kafkamock
